[project]
name = "client-api"
version = "0.1.0"
description = "Add your description here"
requires-python = "~=3.9"
dependencies = [
    "lorem>=0.1.1",
    "pandas>=2.2.3",
    "plotext>=5.3.2",
    "pyswagger>=0.8.39",
    "requests>=2.32.3",
    "requests-toolbelt>=1.0.0",
    "sets>=0.3.2",
]
